language: java

sudo: true

dist: trusty

jdk: openjdk11

before_install:
  - chmod a+x ./mvnw

#script: ./mvnw clean install

jobs:
  include:
    - stage: test
      script: ./mvnw clean compile test
    - stage: package
      script: ./mvnw clean compile package
    - stage: build
      script: ./mvnw clean compile package install -DskipTests